var express = require('express');
var menu=require('./menu');
var index=require('./index');
var contact=require('./contact');
var user = require('./user');
var news=require('./news');
//var reservations=require('./reservations');
var home=require('./home');
var login=require('./login');
var admin=require('./admin');
var logout=require('./logout');
var router=express.Router();

router.use('/logout',logout);
router.use('/admin',admin);
router.use('/login',login);
//router.use('/reservations',reservations);
router.use('/news',news);
router.use('/index',index);
router.use('/',index);
router.use('/user',user);
router.use('/contact',contact);
router.use('/menu',menu);
router.use('/home',home);
module.exports = router;