var express = require('express');
var menu=require('./menu');
var index=require('./index');
var reviews=require('./reviews');
var contact=require('./contact');
var users = require('./users');
var news=require('./news');
var reservations=require('./reservations');
var home=require('./home');
var router=express.Router();

router.use('/reservations',reservations);
router.use('/news',news);
router.use('/index',index);
router.use('/',index);
router.use('/reviews',reviews);
router.use('/user',users);
router.use('/contact',contact);
router.use('/menu',menu);
router.use('/home',home);
module.exports = router;